# Import Library

In [4]:
!pip install rouge_score datasets evaluate

Requirement already satisfied: rouge_score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: evaluate in /usr/local/lib/python3.12/dist-packages (0.4.6)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (0.1.2)

In [5]:
import json
import random
import torch
import evaluate
import pandas as pd
from tqdm import tqdm
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from transformers import DataCollatorForSeq2Seq
from transformers import BartTokenizer, BartForConditionalGeneration
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq
from transformers import BartTokenizer, BartForConditionalGeneration, Trainer, TrainingArguments

# Custom Dataset

In [6]:
path_data = '/content/drive/Shareddrives/My Study Buddy/Pembuatan AI/Dataset/file_summarize_clean.csv'
df = pd.read_csv(path_data)
df

,Unnamed: 0,text,summary,source,text_cleaned,summary_cleaned
0,0,"- Dokter Ryan Thamrin , yang terkenal lewat ac...",Dokter Lula Kamal yang merupakan selebriti sek...,indosum,"- Dokter Ryan Thamrin , yang terkenal lewat ac...",Dokter Lula Kamal yang merupakan selebriti sek...
1,1,handset ini merupakan anggota keluarga ZenFone...,sama dibekali setup kamera ganda di depan . Me...,indosum,handset ini merupakan anggota keluarga ZenFone...,Asus memperkenalkan ZenFone generasi keempat d...
2,2,- Dinas Pariwisata Provinsi Bengkulu kembali m...,10 November 2017 yang lalu . Kegiatan yang ber...,indosum,- Dinas Pariwisata Provinsi Bengkulu kembali m...,Dinas Pariwisata Provinsi Bengkulu kembali men...
3,3,Indonesia Corruption Watch ICW meminta Komisi ...,"KTP , Johannes Marliem dan menjelaskan kepada ...",indosum,Indonesia Corruption Watch ICW meminta Komisi ...,Indonesia Corruption Watch ICW meminta Komisi ...
4,4,Presiden Joko Widodo Jokowi memimpin upacara p...,bagi sepeda kepada tamu undangan yang mengenak...,indosum,Presiden Joko Widodo Jokowi memimpin upacara p...,Jokowi memimpin upacara penurunan bendera . Us...
...,...,...,...,...,...,...
11511,11559,teror terbesar dalam sejarah Australia dilangs...,Sedikitnya seorang pria bersenjata menyandera ...,xlsum,teror terbesar dalam sejarah Australia dilangs...,Sedikitnya seorang pria bersenjata menyandera ...
11512,11560,"sama dengan Boediono selaku Gubernur BI, Miran...","Mantan Deputi Gubernur Bank Indonesia, Budi Mu...",xlsum,"sama dengan Boediono selaku Gubernur BI, Miran...","Mantan Deputi Gubernur Bank Indonesia, Budi Mu..."
11513,11561,Yahudi tidak dapat hidup. Acara di Berlin terj...,"Yahudi, sementara terjadi peningkatan serangan...",xlsum,Yahudi tidak dapat hidup. Acara di Berlin terj...,Kanselir Jerman Angela Merkel mulai berbicara ...
11514,11562,lagi Seydou Keita menyelamatkan AS Roma dari k...,1 dalam laga pertama babak 16 besar Liga Eropa...,xlsum,lagi Seydou Keita menyelamatkan AS Roma dari k...,Penampilan AS Roma tak kunjung membaik setelah...
11515,11563,baru ini terhadap kelompok Daulah Islamiyah di...,Daulah Islamiyah atau yang sebelumnya dikenal ...,xlsum,baru ini terhadap kelompok Daulah Islamiyah di...,Daulah Islamiyah atau yang sebelumnya dikenal ...

In [7]:
# convert text ke token model
tokenizer = BartTokenizer.from_pretrained('facebook/bart-base')

# load pretrained model
model = BartForConditionalGeneration.from_pretrained('facebook/bart-base')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

vocab.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/558M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/259 [00:00<?, ?it/s]

In [8]:
class SummaryDataset(Dataset):
    def __init__(self, tokenizer, data, max_source_length=512, max_target_length=150):
        self.tokenizer = tokenizer
        self.data = data
        self.max_source_length = max_source_length
        self.max_target_length = max_target_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data.iloc[idx]
        text = item['text_cleaned']
        summary = item['summary_cleaned']

        source = self.tokenizer(
            text,
            max_length=self.max_source_length,
            truncation=True
        )

        target = self.tokenizer(
            summary,
            max_length=self.max_target_length,
            truncation=True
        )

        return {
            'input_ids': source['input_ids'],
            'attention_mask': source['attention_mask'],
            'labels': target['input_ids']
        }

In [9]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

In [10]:
train_dataset = SummaryDataset(tokenizer, train_df)
test_dataset = SummaryDataset(tokenizer, test_df)

In [11]:
train_dataset[0]

{'input_ids': [0,
  29,
  16231,
  1168,
  1423,
  1097,
  7252,
  783,
  385,
  22966,
  337,
  1021,
  459,
  298,
  7821,
  991,
  415,
  967,
  17144,
  4,
  208,
  2961,
  449,
  3644,
  181,
  3314,
  2399,
  811,
  16207,
  18217,
  11,
  118,
  26951,
  677,
  2269,
  267,
  523,
  4970,
  260,
  6,
  449,
  1322,
  2133,
  2269,
  1097,
  29183,
  475,
  677,
  282,
  12837,
  19676,
  895,
  385,
  967,
  594,
  895,
  3371,
  4,
  6579,
  11,
  118,
  449,
  625,
  1097,
  604,
  219,
  922,
  405,
  11334,
  3298,
  118,
  9198,
  2348,
  1423,
  1097,
  19267,
  424,
  955,
  13163,
  7372,
  8318,
  2543,
  271,
  11,
  118,
  385,
  7375,
  3494,
  354,
  853,
  604,
  710,
  1182,
  1236,
  225,
  354,
  16207,
  18217,
  20435,
  14548,
  6629,
  1906,
  11334,
  7587,
  1350,
  26012,
  43983,
  1906,
  895,
  7670,
  438,
  9063,
  16207,
  18217,
  12,
  29,
  16231,
  1168,
  1423,
  1097,
  449,
  710,
  1097,
  385,
  22966,
  337,
  385,
  1512,
  7670,
  3914,
  677,
  2279,
  2636,
  4,
  6202,
  18217,
  385,
  31126,
  6202,
  18217,
  12,
  29,
  16231,
  1168,
  1423,
  1097,
  741,
  3785,
  677,
  8512,
  879,
  677,
  260,
  385,
  23590,
  7821,
  991,
  415,
  4151,
  6,
  449,
  710,
  1097,
  2084,
  428,
  4001,
  579,
  3914,
  1439,
  326,
  895,
  879,
  32819,
  2583,
  11188,
  1176,
  14119,
  449,
  9707,
  35223,
  4,
  8958,
  2133,
  1423,
  1097,
  2084,
  428,
  4001,
  19300,
  23590,
  1236,
  20851,
  2982,
  2399,
  677,
  260,
  385,
  23590,
  842,
  267,
  783,
  30166,
  16207,
  18217,
  2269,
  579,
  2531,
  4,
  6202,
  18217,
  14719,
  417,
  281,
  3994,
  260,
  326,
  5219,
  22,
  48883,
  3069,
  3494,
  113,
  22,
  22,
  6202,
  18217,
  12,
  29,
  16231,
  1168,
  1423,
  1097,
  385,
  405,
  710,
  6435,
  260,
  385,
  1512,
  23,
  1180,
  13235,
  1588,
  3069,
  3494,
  326,
  5219,
  22,
  48883,
  3069,
  3494,
  1297,
  1385,
  281,
  1350,
  326,
  5219,
  5730,
  895,
  821,
  5219,
  4,
  36415,
  677,
  69,
  260,
  741,
  895,
  2739,
  16207,
  18217,
  12,
  29,
  16231,
  1168,
  11,
  118,
  6821,
  154,
  2269,
  31002,
  1545,
  11334,
  3069,
  3494,
  6756,
  879,
  3494,
  20187,
  2583,
  260,
  4,
  6202,
  18217,
  1423,
  1097,
  604,
  6276,
  895,
  7321,
  449,
  6841,
  23,
  1180,
  7321,
  449,
  23935,
  6202,
  18217,
  12,
  29,
  16231,
  1168,
  6,
  842,
  11497,
  118,
  2156,
  1423,
  1097,
  604,
  6276,
  895,
  7321,
  642,
  2095,
  4005,
  257,
  579,
  8539,
  23,
  1180,
  842,
  8667,
  967,
  2855,
  102,
  4,
  255,
  5219,
  449,
  710,
  1545,
  6202,
  18217,
  12,
  29,
  16231,
  1168,
  1423,
  1097,
  385,
  36907,
  11632,
  11334,
  2269,
  579,
  26114,
  2628,
  20355,
  44243,
  14286,
  23,
  1180,
  364,
  2258,
  13529,
  118,
  6,
  3834,
  337,
  2855,
  102,
  3023,
  479,
  6202,
  18217,
  10306,
  11334,
  23315,
  2951,
  1423,
  1097,
  784,
  1851,
  6202,
  18217,
  12,
  29,
  16231,
  1168,
  1423,
  1097,
  26951,
  677,
  1385,
  281,
  1350,
  449,
  27586,
  6249,
  12,
  330,
  27586,
  6249,
  842,
  8494,
  22383,
  102,
  4,
  6202,
  18217,
  14719,
  417,
  281,
  3994,
  260,
  23315,
  2951,
  163,
  3785,
  677,
  16207,
  18217,
  7821,
  991,
  415,
  4151,
  14719,
  417,
  281,
  3994,
  260,
  181,
  2095,
  6,
  23,
  1180,
  13235,
  1588,
  3069,
  3494,
  6,
  23315,
  2951,
  385,
  23590,
  4091,
  18531,
  31402,
  1342,
  257,
  4,
  13379,
  811,
  11,
  118,
  26012,
  257,
  415,
  16207,
  18217,
  12,
  29,
  16231,
  1168,
  9031,
  1043,
  424,
  24,
  257,
  6,
  1385,
  281,
  1350,
  16207,
  18217,
  1423,
  1097,
  13235,
  1588,
  3069,
  3494,
  23315,
  2951,
  8470,
  8667,
  967,
  4,
  163,
  3785,
  677,
  23315,
  2951,
  26012,
  20391,
  219,
  1439,
  475,
  677,
  2133,
  449,
  261,
  2987,
  29,
  6073,
  385,
  23590,
  14719,
  14118,
  1439,
  2],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'labels': [0,
  495,
  23590,
  7821,
  991,
  415,
  4151,
  6821,
  154,
  8512,
  879,
  677,
  260,
  16207,
  18217,
  12,
  29,
  16231,
  1168,
  1423,
  1097,
  7252,
  783,
  385,
  22966,
  337,
  1021,
  459,
  298,
  7821,
  991,
  415,
  967,
  17144,
  4,
  208,
  2961,
  449,
  3644,
  181,
  3314,
  2399,
  811,
  16207,
  18217,
  11,
  118,
  26951,
  677,
  2269,
  267,
  523,
  4970,
  260,
  6,
  449,
  1322,
  2133,
  2269,
  1097,
  29183,
  475,
  677,
  282,
  12837,
  19676,
  895,
  385,
  967,
  594,
  895,
  3371,
  4,
  6579,
  11,
  118,
  449,
  625,
  1097,
  604,
  219,
  922,
  405,
  11334,
  3298,
  118,
  9198,
  2348,
  1423,
  1097,
  19267,
  424,
  955,
  13163,
  7372,
  8318,
  2543,
  271,
  11,
  118,
  385,
  7375,
  3494,
  354,
  853,
  604,
  710,
  1182,
  1236,
  225,
  354,
  16207,
  18217,
  20435,
  14548,
  6629,
  1906,
  11334,
  7587,
  1350,
  26012,
  43983,
  1906,
  895,
  7670,
  438,
  9063,
  16207,
  18217,
  12,
  29,
  16231,
  1168,
  1423,
  1097,
  449,
  710,
  1097,
  385,
  22966,
  337,
  385,
  1512,
  7670,
  3914,
  677,
  2279,
  2636,
  4,
  2]}

# Fine tuning model

In [12]:
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

training_args = Seq2SeqTrainingArguments(
    output_dir='/content/drive/Shareddrives/My Study Buddy/Pembuatan AI/Notebooks/results',
    num_train_epochs=2,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    report_to='none',
    # --- TAMBAHAN KRUSIAL ---
    predict_with_generate=True,
    fp16=True
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [13]:
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    processing_class=tokenizer,
    data_collator=data_collator # Masukkan collator-nya di sini
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=2304, training_loss=1.6943884421553876, metrics={'train_runtime': 974.6529, 'train_samples_per_second': 18.903, 'train_steps_per_second': 2.364, 'total_flos': 5616677892833280.0, 'train_loss': 1.6943884421553876, 'epoch': 2.0})

# Evaluasi Model

In [14]:
rouge_metric = evaluate.load('rouge')

def generate_summaries_batch(model, tokenizer, dataset, data_collator, batch_size=8):
    model.eval()
    summaries = []

    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        collate_fn=data_collator,
        shuffle=False
    )

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Membuat Ringkasan"):
            input_ids = batch['input_ids'].to(model.device)
            attention_mask = batch['attention_mask'].to(model.device)

            outputs = model.generate(
                input_ids,
                attention_mask=attention_mask,
                max_length=150,
                num_beams=4,
                early_stopping=True,
                decoder_start_token_id=tokenizer.bos_token_id
            )

            # decode
            batch_summaries = [tokenizer.decode(ids, skip_special_tokens=True) for ids in outputs]
            summaries.extend(batch_summaries)

    return summaries

Downloading builder script: 0.00B [00:00, ?B/s]

In [15]:
actual_summaries = test_df['summary_cleaned'].tolist()

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)
print("Mulai proses inferensi batch...")
generated_summaries = generate_summaries_batch(
    model,
    tokenizer,
    test_dataset,
    data_collator,
    batch_size=8
)

print("\nMenghitung Skor ROUGE...")
rouge_score = rouge_metric.compute(predictions=generated_summaries, references=actual_summaries)

Mulai proses inferensi batch...

Membuat Ringkasan: 100%|██████████| 288/288 [18:16<00:00,  3.81s/it]

Menghitung Skor ROUGE...

In [16]:
print(rouge_score)

{'rouge1': np.float64(0.37202191445122795), 'rouge2': np.float64(0.26754098673539595), 'rougeL': np.float64(0.3314201925903299), 'rougeLsum': np.float64(0.33199098554771417)}

In [17]:
print("=== CEK ISI PREDIKSI (3 Data Pertama) ===")
for i, teks in enumerate(generated_summaries[:3]):
    print(f"Prediksi {i+1}: '{teks}'")

print("\n=== CEK ISI REFERENSI (3 Data Pertama) ===")
for i, teks in enumerate(actual_summaries[:3]):
    print(f"Referensi {i+1}: '{teks}'")

=== CEK ISI PREDIKSI (3 Data Pertama) ===
Prediksi 1: 'Juara dunia Grand Prix sepeda motor 500cc 1993 , Kevin Schwantz , menganggap Maverick Vinales punya tantangan besar dalam usahanya merebut gelar juara di MotoGP 2017 . Tantangan utama yang harus dihadapi vinales adalah beradu taktik melawan Valentino Rossi dan Marquez . Vinalees menjadi salah satu kandidat juara musim ini . Hingga paruh musim 2017 , mantan pebalap Suzuki itu mampu meraih tiga kemenangan dan berada di posisi kedua klasemen sementara hing'
Prediksi 2: 'Pengakuan tersebut datang ketika Nolan tengah diwawancarai oleh saudaranya , Jonathan , untuk sebuah materi promo Dunkirk . Nolan mengakui , ketika melakukan riset untuk film Tersebut , ia amat tertarik pada detail kisah evakuasi tentara Sekutu itu sehingga sangat percaya diri dapat menggarapnya tanpa naskah . Namun justru itulah yang ia usulkan kepada Crowley dan Thomas .'
Prediksi 3: 'Pelatih legendaris AC Milan , Fabio Capello 70 , mengaku ingin memeluk Gianluigi Donnarumma 18 yang melakukan blunder dalam pertandingan Liga Italia kontra Pescara di Stadion Adriatico , Minggu 2 4 2017 . Dia gagal mengontrol bola hasil back - pass bek Gabriel Paletta hingga si kulit bulat bergulir masuk ke gawangnya sendiri . Insiden itu menghasilkan gol bunuh diri yang tercatat atas nama Paletta menit ke - 12 .'

=== CEK ISI REFERENSI (3 Data Pertama) ===
Referensi 1: 'Juara dunia Grand Prix sepeda motor 500cc 1993 , Kevin Schwantz , menganggap Maverick Vinales punya tantangan besar dalam usahanya merebut gelar juara dunia MotoGP 2017 . Tantangan utama yang harus dihadapi Vinales adalah beradu taktik melawan Valentino Rossi dan Marquez . Vinales menjadi salah satu kandidat juara musim ini . Hingga paruh musim 2017 , mantan pebalap Suzuki itu mampu meraih tiga kemenangan .'
Referensi 2: 'Sutradara Dunkirk , Christopher Nolan , ternyata sempat punya ide untuk membuat film tentang Perang Dunia II tersebut lebih alamiah . Pengakuan tersebut datang ketika Nolan tengah diwawancarai oleh saudaranya , Jonathan , untuk sebuah materi promo Dunkirk . Ia mengakui , ketika melakukan riset untuk film tersebut , ia amat tertarik pada detail kisah evakuasi tentara Sekutu itu sehingga sangat percaya diri dapat menggarapnya tanpa naskah .'
Referensi 3: 'Pelatih legendaris AC Milan , Fabio Capello 70 , mengaku ingin memeluk Gianluigi Donnarumma 18 yang melakukan blunder dalam pertandingan Liga Italia kontra Pescara di Stadion Adriatico , Minggu 2 4 2017 . Duel yang berakhir imbang dengan skor 1 - 1 tersebut diwarnai oleh blunder kiper muda AC Milan , Gianluigi Donnarumma . Dia gagal mengontrol bola hasil back - pass bek Gabriel Paletta hingga si kulit bulat bergulir masuk ke gawangnya sendiri .'

In [18]:
print("\n=== HASIL EVALUASI ROUGE ===")
print(f"ROUGE-1 : {rouge_score['rouge1'] * 100:.2f}%")
print(f"ROUGE-2 : {rouge_score['rouge2'] * 100:.2f}%")
print(f"ROUGE-L : {rouge_score['rougeL'] * 100:.2f}%")

=== HASIL EVALUASI ROUGE ===
ROUGE-1 : 37.20%
ROUGE-2 : 26.75%
ROUGE-L : 33.14%

# Save Model

In [19]:
import os

folder_penyimpanan = "/content/drive/Shareddrives/My Study Buddy/Pembuatan AI/Notebooks/model2"

os.makedirs(folder_penyimpanan, exist_ok=True)

print("Sedang mengekspor model ke Google Drive...")
model.save_pretrained(folder_penyimpanan)
tokenizer.save_pretrained(folder_penyimpanan)

print(f"🎉 Selesai! Model berhasil disimpan di:\n{folder_penyimpanan}")

Sedang mengekspor model ke Google Drive...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

🎉 Selesai! Model berhasil diselamatkan secara permanen di:
/content/drive/Shareddrives/My Study Buddy/Pembuatan AI/Notebooks/model2

# Export Model
Model disimpan ke dalam format ONNX

In [3]:
# install dependencies
!pip install optimum[onnx]
!pip install onnx onnxruntime

Requirement already satisfied: optimum[onnx] in /usr/local/lib/python3.12/dist-packages (2.1.0)
Requirement already satisfied: transformers>=4.29 in /usr/local/lib/python3.12/dist-packages (from optimum[onnx]) (4.57.6)
Requirement already satisfied: torch>=1.11 in /usr/local/lib/python3.12/dist-packages (from optimum[onnx]) (2.10.0+cu128)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from optimum[onnx]) (26.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optimum[onnx]) (2.0.2)
Requirement already satisfied: huggingface_hub>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from optimum[onnx]) (0.36.2)
Requirement already satisfied: optimum-onnx in /usr/local/lib/python3.12/dist-packages (from optimum[onnx]) (0.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnx]) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnx]) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnx]) (1.4.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnx]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnx]) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnx]) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnx]) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnx]) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11->optimum[onnx]) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.29->optimum[onnx]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.29->optimum[onnx]) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.29->optimum[onnx]) (0.7.0)
Requirement already satisfied: onnx in /usr/local/lib/python3.12/dist-packages (from optimum-onnx->optimum[onnx]) (1.21.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11->optimum[onnx]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11->optimum[onnx]) (3.0.3)
Requirement already satisfied: protobuf>=4.25.1 in /usr/local/lib/python3.12/dist-packages (from onnx->optimum-onnx->optimum[onnx]) (5.29.6)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx->optimum-onnx->optimum[onnx]) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnx]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnx]) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnx]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnx]) (2026.4.22)
Requirement already satisfied: onnx in /usr/local/lib/python3.12/dist-packages (1.21.0)
Collecting onnxruntime
  Downloading onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.12/dist-packages (from onnx) (2.0.2)
Requirement already satisfied: protobuf>=4.25.1 in /usr/local/lib/python3.12/dist-packages (from onnx) (5.29.6)
Requirement already satisfied: typing_extensions>=4.7.1 in /usr/local/lib/python3.12/dist-packages (from onnx) (4.15.0)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx) (0.5.4)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (25.12.19)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (26.1)
Downloading onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 65.7 MB/s eta 0:00:00
Installing collected packages: onnxruntime
Successfully installed onnxruntime-1.26.0

In [4]:
!optimum-cli export onnx \
  --model "/content/drive/Shareddrives/My Study Buddy/Pembuatan AI/Notebooks/model2" \
  --task text2text-generation \
  "/content/drive/Shareddrives/My Study Buddy/Pembuatan AI/Productions/Model2"

2026-05-23 13:23:25.456160: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Multiple distributions found for package optimum. Picked distribution: optimum-onnx
Flax classes are deprecated and will be removed in Diffusers v1.0.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.
Flax classes are deprecated and will be removed in Diffusers v1.0.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.
`torch_dtype` is deprecated! Use `dtype` instead!
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:196: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  inverted_mask = torch.tensor(1.0, dtype=dtype) - expanded_mask
/usr/local/lib/python3.12/dist-packages/transformers/integrations/sdpa_attention.py:81: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  is_causal = query.shape[2] > 1 and attention_mask is None and getattr(module, "is_causal", True)
/usr/local/lib/python3.12/dist-packages/transformers/models/bart/modeling_bart.py:664: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if sequence_length != 1:
Could not find ONNX initializer for torch parameter model.encoder.embed_tokens.weight. model.encoder.embed_tokens.weight will not be checked for deduplication.
Found different candidate ONNX initializers (likely duplicate) for the tied weights:
	lm_head.weight: {'onnx::MatMul_1876'}
	model.decoder.embed_tokens.weight: {'model.shared.weight'}
	model.encoder.embed_tokens.weight: set() --> ignored (may be a parameter from a part of the model not exported)
	model.shared.weight: {'model.shared.weight'}
		-[x] values not close enough, max diff: 2.86102294921875e-05 (atol: 1e-05)
The ONNX export succeeded with the warning: The maximum absolute difference between the output of the reference model and the ONNX exported model is not within the set tolerance 1e-05:
- logits: max diff = 2.86102294921875e-05.
 The exported model was saved at: /content/drive/Shareddrives/My Study Buddy/Pembuatan AI/Productions/Model2